import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/footer";
import AuthProvider from "@/services/AuthProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    default: "Car Doctor Pro",
    template: "%s | Car Doctor Pro"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='carDoctorTheme'>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container items-center`}>
          <ToastContainer/>
           <AuthProvider>
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
            </AuthProvider>
      </body>

    </html>
  );
}
